site_name: Linux Survival Guide 
copyright: Copyright (c) 2025 nyarkus_, zedzad14
repo_url: https://github.com/nyarkus/lsg

exclude_docs: overrides/
docs_dir: docs/

theme:
  logo: assets/archlinux-1024.png
  favicon: assets/archlinux-1024.png
  custom_dir: docs/overrides
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep purple
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep purple
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - extensions.pkg_extension

plugins:
  - search
  - table-reader
  - git-authors
  - git-revision-date-localized:
      # type: timeago
      enable_creation_date: true
      # enable_short_rev: true

extra_javascript:
  - assets/js/views-counter.js
extra_css:
  - assets/css/package.css